language: python
python:
  - "2.7"
install:
  - "ln -s localsettings_travis.py trytry/localsettings.py"
  - "pip install -q -e . --use-mirrors"
  - "pip install -q -r requirements.pip --use-mirrors"
script: "python manage.py test simple_python"
