language: python
python:
  - "2.7"
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq --yes --force-yes timelimit"
install:
  - "ln -s localsettings_travis.py trytry/localsettings.py"
  - "pip install -q -e . --use-mirrors"
  - "pip install -q -r requirements.pip --use-mirrors"
script: "python manage.py test -v2 core simple_python simple_bash"
